ALTER TABLE themes ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE themes ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE themes ADD COLUMN IF NOT EXISTS contact_email TEXT;
ALTER TABLE themes ADD COLUMN IF NOT EXISTS hours TEXT;
ALTER TABLE themes ADD COLUMN IF NOT EXISTS location_url TEXT;
